micronaut:
  application:
    name: room-sample-2
  server:
    port: 8004
  router:
    static-resources: 
        default:
            enabled: false

  http:
    services:
      stats:
        url: 'http://127.0.0.1:8002/stats/'

netty:
  default:
    allocator:
      max-order: 3
