name: Test inventory

on:
  push:
    paths:
      - 'inventory/**'
      - '.github/workflows/inventory.yml'
  pull_request:
    paths:
      - 'inventory/**'
      - '.github/workflows/inventory.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8.0
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('Java/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and test
      working-directory: inventory
      run: mvn -B test
