name: Test room-sample-2

on:
  push:
    paths:
      - 'room-sample-2/**'
      - '.github/workflows/room-sample-2.yml'
  pull_request:
    paths:
      - 'room-sample-2/**'
      - '.github/workflows/room-sample-2.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 8.0
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('room-sample-2/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and test
      working-directory: room-sample-2
      run: mvn -B package

    - name: Smoke test
      working-directory: room-sample-2
      run: |
        java -jar target/rogue-room-sample-2-1.0-SNAPSHOT.jar &
        sleep 2
        wget -qO ./response.json http://localhost:8004/empty/
        pkill -f "rogue-room-sample"
        cat response.json

    - name: Room testing
      working-directory: room-sample-2
      run: |
        java -jar target/rogue-room-sample-2-1.0-SNAPSHOT.jar &
        sleep 2
        docker run --network=host "codecop/rogue-room-tester" http://localhost:8004/key/
        pkill -f "rogue-room-sample"
