name: Test runtime

on:
  push:
    paths:
      - 'runtime/**'
      - '.github/workflows/runtime.yml'
  pull_request:
    paths:
      - 'runtime/**'
      - '.github/workflows/runtime.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up dependencies
      working-directory: runtime
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test
      working-directory: runtime
      run: python -m unittest
