name: Test stats

on:
  push:
    paths:
      - 'stats/**'
      - '.github/workflows/stats.yml'
  pull_request:
    paths:
      - 'stats/**'
      - '.github/workflows/stats.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 15.x
    - name: Cache Node packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('stats/package.json') }}
        restore-keys: ${{ runner.os }}-npm
    - name: Set up dependencies
      working-directory: stats
      run: npm install

    - name: Build and test
      working-directory: stats
      run: |
        npm run build
        npm test

    - name: Smoke test
      working-directory: stats
      run: |
        node ./dist/index.js &
        sleep 1
        wget -qO ./response.json http://localhost:8002/stats/hp
        pkill -f "index.js"
        cat response.json

    - name: Build Docker image
      working-directory: stats
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/rogue-stats:latest
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rogue-stats:latest

    - name: Push Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/rogue-stats
        readme-filepath: ./stats/README.md
