name: Test template-java-spark

on:
  push:
    paths:
      - 'template-java-spark/**'
      - '.github/workflows/template-java-spark.yml'
  pull_request:
    paths:
      - 'template-java-spark/**'
      - '.github/workflows/template-java-spark.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('Java/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and test
      working-directory: template-java-spark
      run: mvn -B test
