name: Test template-python-flask

on:
  push:
    paths:
      - 'template-python-flask/**'
      - '.github/workflows/template-python-flask.yml'
  pull_request:
    paths:
      - 'template-python-flask/**'
      - '.github/workflows/template-python-flask.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.11", "3.12", "3.12"]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up dependencies
      working-directory: template-python-flask
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test
      working-directory: template-python-flask
      run: python -m pytest

    - name: Smoke test
      working-directory: template-python-flask
      run: |
        python main.py &
        sleep 1
        wget -qO ./response.json http://localhost:5000/hello
        wget -q --method POST http://localhost:5000/hello?name=Peter
        wget -qO ./response2.json http://localhost:5000/hello
        pkill -f "main.py"
        sleep 1
        cat response.json
        cat response2.json
