name: Test template-php-lumen

on:
  push:
    paths:
      - 'template-php-lumen/**'
      - '.github/workflows/template-php-lumen.yml'
  pull_request:
    paths:
      - 'template-php-lumen/**'
      - '.github/workflows/template-php-lumen.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["7.3", "7.4", "8.0", "8.2", "8.4"]
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: Set up dependencies
      working-directory: template-php-lumen
      run: composer install

    - name: Test
      working-directory: template-php-lumen
      run: ./vendor/bin/phpunit

    - name: Smoke test
      working-directory: template-php-lumen
      run: |
        php -S localhost:8000 -t bootstrap &
        sleep 1
        wget -qO ./response.json http://localhost:8000/hello
        wget -q --method POST http://localhost:8000/hello?name=Peter
        wget -qO ./response2.json http://localhost:8000/hello
        pkill -f "localhost:8000"
        sleep 1
        cat response.json
        cat response2.json
