name: Test template-java-micronaut

on:
  push:
    paths:
      - 'template-java-micronaut/**'
      - '.github/workflows/template-java-micronaut.yml'
  pull_request:
    paths:
      - 'template-java-micronaut/**'
      - '.github/workflows/template-java-micronaut.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [8, 11, 17, 21, 23]
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('template-java-micronaut/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and test
      working-directory: template-java-micronaut
      run: mvn -B package

    - name: Smoke test
      working-directory: template-java-micronaut
      run: |
        java -jar target/rogue-template-micronaut-1.0-SNAPSHOT.jar &
        sleep 2
        wget -qO ./response.json http://localhost:8080/hello
        wget -q --method POST http://localhost:8080/hello?name=Peter
        wget -qO ./response2.json http://localhost:8080/hello
        pkill -f "rogue-template-micronaut"
        sleep 1
        cat response.json
        cat response2.json
