name: Test template-ts-express

on:
  push:
    paths:
      - 'template-ts-express/**'
      - '.github/workflows/template-ts-express.yml'
  pull_request:
    paths:
      - 'template-ts-express/**'
      - '.github/workflows/template-ts-express.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14, 16, 18]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('template-ts-express/package.json') }}
        restore-keys: ${{ runner.os }}-npm
    - name: Set up dependencies
      working-directory: template-ts-express
      run: npm install

    - name: Build and test
      working-directory: template-ts-express
      run: |
        npm run build
        npm test
