name: Test template-io-yown

on:
  push:
    paths:
      - 'template-io-yown/**'
      - '.github/workflows/template-io-yown.yml'
  pull_request:
    paths:
      - 'template-io-yown/**'
      - '.github/workflows/template-io-yown.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Io dependencies
      working-directory: template-io-yown
      run: |
        sudo apt-get install build-essential cmake libpcre3-dev libevent-dev
        # link to newer libevent 2.1.x
        ls -la /usr/lib/x86_64-linux-gnu/libevent*.so.*
        sudo ln -s /usr/lib/x86_64-linux-gnu/libevent-2.1.so.7.0.1 /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5

    - name: Set up Io
      run: |
        wget -q http://iobin.suspended-chord.info/linux/iobin-linux-x64-deb-current.zip
        unzip -qq iobin-linux-x64-deb-current.zip
        sudo dpkg -i IoLanguage-2013.11.04-Linux-x64.deb
        sudo ldconfig
        io --version

    - name: Set up dependencies
      run: |
        io -e "System installPrefix println"
        git clone https://github.com/codecop/Json.git
        sudo mv Json /usr/local/lib/io/addons/
        io -e "Json"
        git clone https://github.com/codecop/Yown.git
        sudo mv Yown /usr/local/lib/io/addons/
        io -e "Yown"

    - name: Test
      working-directory: template-io-yown
      run: io ./tests/correctness/run.io

    - name: Smoke test
      working-directory: template-io-yown
      run: |
        io ./io/main.io &
        sleep 1
        wget -qO ./response.json http://localhost:8010/hello
        pkill -f "main.io"
        cat response.json
