name: Test template-go-http

on:
  push:
    paths:
      - 'template-go-http/**'
      - '.github/workflows/template-go-http.yml'
  pull_request:
    paths:
      - 'template-go-http/**'
      - '.github/workflows/template-go-http.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.16', '1.18', '1.20', '1.22' , '1.24']
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Cache Go packages
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('template-go-http/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - name: Build and test
      working-directory: template-go-http
      run: |
        cd hello
        go test -v
        cd ..
        go build

    - name: Smoke test
      working-directory: template-go-http
      run: |
        ./roguelike-go &
        sleep 1
        wget -qO ./response.json http://localhost:8080/get_name
        wget -q --method POST http://localhost:8080/set_name?name=Peter
        wget -qO ./response2.json http://localhost:8080/get_name
        pkill -f "roguelike-go"
        sleep 1
        cat response.json
        cat response2.json
